api:
  endpoint: "https://timeapi.io/api/v1/time/current/zone?timezone="
  continent: "Europe/London"

server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: root
    password: test